# Generated by Django 3.1.7 on 2021-04-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=25)),
                ('image', models.ImageField(upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('sold_out', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('EL', 'Electronic')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
